version: '3.2'
services:
  jenkins:
    image: jenkinsci/jenkins
    volumes:
      - ./jenkins:/var/jenkins_home:rw
    ports:
      - 8080:8080
    container_name: jenkins

  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    container_name: sonarqube
